/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anoah_ndkdemoproject_NdkU */

#ifndef _Included_com_anoah_ndkdemoproject_NdkU
#define _Included_com_anoah_ndkdemoproject_NdkU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anoah_ndkdemoproject_NdkU
 * Method:    getStringHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_anoah_ndkdemoproject_NdkU_getStringHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
